# Don't change this! Version used to track needed updates.
version = 2

[disabler]
disabledEnchantmentsV2 = [
    [ "nova_structures:antidote", { table = false, loot = false, trade = false } ],
    [ "nova_structures:conductivity_curse", { table = false, loot = false, trade = false } ],
    [ "nova_structures:ghasted", { table = false, loot = false, trade = false } ],
    [ "nova_structures:gravity", { table = false, loot = false, trade = false } ],
    [ "nova_structures:illagers_bane", { table = false, loot = false, trade = false } ],
    [ "nova_structures:multishot", { table = false, loot = false, trade = false } ],
    [ "nova_structures:outreach", { table = false, loot = false, trade = false } ],
    [ "nova_structures:photosynthesis", { table = false, loot = false, trade = false } ],
    [ "nova_structures:piercing", { table = false, loot = false, trade = false } ],
    [ "nova_structures:power", { table = false, loot = false, trade = false } ],
    [ "nova_structures:traveler", { table = false, loot = false, trade = false } ],
    [ "nova_structures:wax_wings", { table = false, loot = false, trade = false } ],
    [ "nova_structures:wither_coated", { table = false, loot = false, trade = false } ]
]
disabledEnchantments = [  ]

[maxLevel]
maxLevels = [  ]
globalMaxLevel = 0
limitObtainableEnchantmentLevel = false
obtainableEnchantmentLevels = [  ]

[trades]
limitBookTradeLevel = false
bookTradeLevelLimit = 5
modifyEnchantedBookTradeUses = false
maxEnchantedBookTradeUses = 12
modifyEnchantedItemTradeUses = false
maxEnchantedItemTradeUses = 3
enchantedBookTradeRestockEnabled = true
enchantedItemTradeRestockEnabled = true

[enchantingTable]
enchantingTableEnabled = true
modifyMaxTablePower = false
maxTablePower = 15
modifyLapisCost = false
lapisCostFormula = "i+1"
modifyXpCost = false
xpCostFormula = "i+1"

[loot]
modifyEnchantWithLevelsMaxPower = false
enchantWithLevelsMaxPower = 50