name = "red"
author = "congig n cooki"
version = "1.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73fd250f684d2b9ca1d47af0a72decc98c0fbbc653828c840dbe18f826ec4f55"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
