name = "red"
author = "congig n cooki"
version = "1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "820812ef3a36b1a071b2a9dbe20a893bc14ceaa539e361a0bf4b5205767267a4"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
