name = "red"
author = "congig n cooki"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7e98b502236bfa4c7d6cc3b2b2ea8ef55ee85f16cbf49a966b6a7a33893a838"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
