name = "red"
author = "congig n cooki"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bce15c4cafdee15e8d83bc6932bf3768c0663fa02217fe32da9b0e6304889b8"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
