name = "red"
author = "congig n cooki"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4958f08406de2b52fa0c4c54bb6963b5a34c0d3976e80d811ce5a76ea24c319c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
