name = "red"
author = "congig n cooki"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b8ad1474978e6b343f140a4556ff6583c4d55e95b8cfbc427769a612c20dedd"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
