name = "red"
author = "congig n cooki"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "243e09e0423b9a9ce1c6f1717d8d676bbbf34b02aee01608475db4db7950698b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
