name = "red"
author = "congig n cooki"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a0d07631066760a61af964e21bed2eeaff282ef705fdcb1fcc0acfcecb9c392"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
