name = "red"
author = "congig n cooki"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "681614a18d65e1fa1996ac8af57201b4c004259474581f00d166a1400028128b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
