name = "red"
author = "congig n cooki"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61f5d505f760a2f5e7e0fd21351507421f43749cce37e7662d362e2ffdc4fb2c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
