name = "red"
author = "congig n cooki"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "566a517ccbd56867d9aceaf6f289e696e8fe87a1d2621fe347496ad80c2b6ac6"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
