name = "red"
author = "congig n cooki"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b49ea8c1d75eece48306be1f8f7073bb5bd693e1027cb836abc4048d5d97ce7"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
