name = "red"
author = "congig n cooki"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6df5a184c95b87be52e86dde655ac4004679582b758cbb1da9936ced49d379f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
