name = "red"
author = "congig n cooki"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8a444043602f9eeb47265178cbd4fcf1e482b136a8a1f71cc1c8cc10a73143a"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
