name = "red"
author = "congig n cooki"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "972dd179ca3661a4a1a97cac7cf5c8a11b3dc69d86fad6fefdba15c60afe524a"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
