name = "red"
author = "congig n cooki"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e56e81ba891bf6565a592f7148beb3393f583fca4e4286c33a2f003ce6e39de"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
