name = "red"
author = "congig n cooki"
version = "1.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e656d3f88ade31c5f070fe0ade8dd037f1c6468c0a03e2e400cd0726a15a55b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
