name = "red"
author = "congig n cooki"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c46ddd4a274434c2a92a46afe115a980369d1131397d2ae284ddd2d23f57e23d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
