name = "red"
author = "congig n cooki"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c61297a9f023bc840f179a92e65efebe3635107c33f7a015d4c1a8729f0a68b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
