name = "red"
author = "congig n cooki"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dbc75eb4c7bba5e49e24935d2c7460cd79ce5f77caae88efd8b4aa19264476d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
