name = "red"
author = "congig n cooki"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7dc4b8b60ce826dfbd911e5a535855e31a6366f00a5ba67acefc071b130ccc45"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
