name = "red"
author = "congig n cooki"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c2b3c6e6268f7796aaaf0bf39fb69c4721e5d7d38a56d0c853f74c37386b8a5"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
