name = "red"
author = "congig n cooki"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7873576de496296b6de45556afd52f2b532214c8eb77480934a57b9867c7e30"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
