name = "red"
author = "congig n cooki"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "867ce27bc07d51d83dbaab9fddcf405add352097159592e3bffc3b016a5b3389"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
