name = "red"
author = "congig n cooki"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b18c898e0c0b366acb96c70d3565c17a2a5a55fb302d4efe4c9e88e7ff71309"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
