name = "red"
author = "congig n cooki"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d802a3915629a9f350535e68f5cc7be76283e3e1f70de3d6af20befec1da8c92"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
